# -*- coding: utf-8 -*-
from odoo import models, fields, api, _
from odoo.exceptions import UserError


class AccountMove(models.Model):
    """Soft-lock layer on top of Odoo's standard ledger (account.move).

    The education finance engine (cc.finance) and the refund workflow
    (cc.finance.refund) post their entries here. account.move IS the single
    source of truth for money; we never track balances in custom tables.

    'Soft Lock' = a validated (posted) move generated by the finance engine
    cannot be deleted by normal users. It can still be removed by a user who
    holds the override right (group_finance_ledger_admin), keeping the
    constraint flexible per the MASTER_PLAN 'Soft Constraints' principle.
    """
    _inherit = "account.move"

    # Back-link to the education finance wrapper that produced this move.
    edu_finance_id = fields.Many2one(
        "cc.finance",
        string="Education Finance Source",
        ondelete="set null",
        index=True,
        copy=False,
    )
    # Back-link to the refund request that produced this credit note.
    edu_refund_id = fields.Many2one(
        "cc.finance.refund",
        string="Education Refund Source",
        ondelete="set null",
        index=True,
        copy=False,
    )

    is_ledger_locked = fields.Boolean(
        string="Ledger Locked",
        compute="_compute_is_ledger_locked",
        store=True,
        help="A posted move created by the education finance engine. "
             "Protected against deletion (soft lock).",
    )

    @api.depends("state", "edu_finance_id", "edu_refund_id")
    def _compute_is_ledger_locked(self):
        for move in self:
            move.is_ledger_locked = bool(
                move.state == "posted"
                and (move.edu_finance_id or move.edu_refund_id)
            )

    def _can_override_ledger_lock(self):
        """Who may bypass the soft lock (the override right)."""
        return self.env.su or self.env.user.has_group(
            "edu_finance.group_finance_ledger_admin"
        )

    def unlink(self):
        locked = self.filtered("is_ledger_locked")
        if locked and not self._can_override_ledger_lock():
            raise UserError(_(
                "These validated ledger entries are protected and cannot be "
                "deleted:\n%(names)s\n\n"
                "This is a soft lock. A user with the 'Finance Ledger Admin' "
                "right can remove them if absolutely necessary; otherwise "
                "reverse them with a credit note instead.",
                names="\n".join("- %s" % m.display_name for m in locked),
            ))
        return super().unlink()
