from . import edu_homework
from . import edu_homework_mark
from . import slide_inherit
from . import edu_homework_submission
from . import res_partner
from . import edu_timetable
from . import edu_student_lesson_report
from . import edu_group_student
from . import edu_group
from . import lesson_complete_wizard
from . import homework_grade_wizard