{
    "name": "UStudy eLearning Homework",
    "version": "1.8.0",
    "summary": "Homework & grading for eLearning lessons",
    "category": "Education",
    "author": "Shohjahon Obruyev",
    "license": "LGPL-3",
    "depends": [
        "base",
        "web",
        "mail",
        "website",
        "hr", 
        "website_slides",
        "ustudy_course",
        "ustudy_group",
        'portal',
    ],
    "data": [
        'security/security.xml',
        "security/ir.model.access.csv",
        "views/edu_homework_views.xml",
        "views/homework_grade_wizard_views.xml",
        "views/edu_lesson_task_views.xml",
        "views/website_homework_templates.xml",
        # "views/student_homeworks_views.xml",
        "views/slide_inherit_views.xml",
        "views/res_partner_student_views.xml",
        # "views/portal_layout.xml",
        'views/portal_my_lessons.xml',
        'views/portal_home.xml',
        "views/edu_group_form_inherit.xml",
        "views/edu_timetable_form_inherit.xml",
        "views/menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "ustudy_homework/static/src/js/lesson_report_dashboard.js",
            "ustudy_homework/static/src/js/attendance_report_list.js",
            "ustudy_homework/static/src/xml/lesson_report_dashboard.xml",
            "ustudy_homework/static/src/css/lesson_report_dashboard.css",
        ],
        "web.assets_frontend": [
            "ustudy_homework/static/src/js/ustudy_homework_tab.js",
            # FullCalendar global build (bundled by web) + the portal calendar
            # initialiser. Path was previously the non-existent .../xml/... file,
            # so the calendar JS never loaded and the page stuck on "loading".
            "web/static/lib/fullcalendar/core/index.global.js",
            "web/static/lib/fullcalendar/daygrid/index.global.js",
            "web/static/lib/fullcalendar/list/index.global.js",
            "ustudy_homework/static/src/js/lesson_calendar.js",
            "ustudy_homework/static/src/css/hide_sidebar.css",
        ],
    },
    'post_init_hook': 'post_init_set_pass_ball',
    "installable": True,
    "application": False,
    "auto_install": False,
}
